### ISSUE TITLE
adding traps

### ISSUE THREAD

**Issue by hassan2050** [toreamun/victor-smart-kill#2]
Any idea how to add a trap to the system using the API without having to go through the Smart Kill app?

**Comment by toreamun** [comment]
It should be possible, but have not spent any time looking at the details. My priority was to create read access to create a [integration](https://github.com/toreamun/amshan-homeassistant) to use in my [Home Assistant](https://www.home-assistant.io/). Now my Sonos speak to me when a mouse is captured ;-) 

I was also a bit worried that using the API to change anything could break the trap/profile configuration. That may not be anything Victor appreciate...

**Comment by hassan2050** [comment]
How did you figure out the API?

Scott


-- Tore Amundsen wrote:
> It should be possible, but have not spent any time looking at the details. My
> priority was to create read access to create a
> [integration](https://github.com/toreamun/amshan-homeassistant) to use in my
> [Home Assistant](https://www.home-assistant.io/). Now my Sonos speak to me
when
> a mouse is captured ;-)
>
> I was also a bit worried that using the API to change anything could break
the

**Comment by toreamun** [comment]
I just looked at the network traffic from my phone when using the app.
